spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbexploristic
    username: root
    password:
  application:
    name: profile-service
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

server:
  port: 8081

clients:
  addressUrl: http://localhost:8082/api/v1/addresses
  contactUrl: http://localhost:8082/api/v1/contact

logging:
  level:
    org:
      springframework: ERROR
    profile:
      exception: ERROR

db:
  dbQueries:
    getProfiles: "select * from profile"
    getProfileById: "select p.profileId,p.userName,p.firstName, p.lastName, p.profileActive, p.contactId,p.addressId, p.profileImage, p.role, c.email, c.phoneNumber from profile p, Contact c where p.profileId=? and c.contactId=p.ContactId"
    getProfileByRole: "select p.profileId,p.userName,p.firstName, p.lastName, p.profileActive, p.contactId,p.addressId, p.profileImage, p.role, c.email, c.phoneNumber from profile p, Contact c where p.role=? and c.contactId=p.ContactId"
    addProfile: "INSERT INTO PROFILE(userName,firstName,lastName,password,addressId,contactId,profileActive,profileImage,role) values (?,?,?,?,?,?,?,?,?)"
    updateprofile: "update profile set userName=?,firstName=?,lastName=?,profileImage=?,role=? where profileId=?"
    updateStatus: "update profile set profileActive=? where profileId=?"
    getProfileId : "select p.profileId,p.userName,p.firstName, p.lastName, p.profileActive, p.contactId,p.addressId, p.profileImage, p.role, c.email, c.phoneNumber from profile p, Contact c where profileId=? and password=? and c.contactId=p.ContactId"
    updatePassword: "UPDATE profile set password=? where profileId=?"
    getLoginState: "select profileId,userName,role,profileActive from profile where username=? and password=?"
    getCheckUsername: "select count(profileId) as profileId from profile where username=?"
    updateProfileImage: "update profile set profileImage=? where profileId=?"