spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbexploristic
    username: root
    password:
  application:
    name: utils-service
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

server:
  port: 8082

clients:
  mailUrl: http://localhost:8084/api/v1/mails

db:
  dbQueries:
    getCategories: "Select * from category"
    insertCategory: "INSERT INTO category(categoryName,categoryDescription,categoryActive,categorySmallIconURL,categoryBigIconURL) VALUES(?,?,?,?,?)"
    updateCategory: "UPDATE category set categoryName=?,categoryDescription=?,categoryActive=?, categorySmallIconURL=?,categoryBigIconURL=? where categoryId=? "
    changeCategoryStatus: "UPDATE category set categoryActive=? where categoryId=?"
    getCategoryCount: "select count(categoryId) from listing where categoryId=? group By listingId"

    insertAddress: "INSERT INTO address(city,state,country,area,addressLine1,addressLine2,pinCode) VALUES(?,?,?,?,?,?,?)"
    updateAddress: "UPDATE address set city=?,state=?,country=?,area=?,addressLine1=?,addressLine2=?,pinCode=? where addressId=? "
    getAddressById: "SELECT * from address where addressId=?"

    insertContact: "INSERT INTO contact(phoneNumber,email,workNumber) VALUES(?,?,?)"
    updateContact: "UPDATE contact set phoneNumber=?,email=?,workNumber=? where contactId=? "
    getContactById: "SELECT * from contact where contactId=?"

    getQueries: "Select * from query"
    insertQuery: "INSERT INTO query(listingId,firstName,lastName,title,message,phoneNumber,email) VALUES(?,?,?,?,?,?,?)"
    getQueriesById: "Select * from query where queryId=?"
    getQueriesByListingId: "Select * from query where listingId=?"
    getQueriesByBusinessId: "select * from query where listingId in(select listingId from listing where profileId=?)"