spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbexploristic
    username: root
    password:
  application:
    name: listing-service
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

server:
  port: 8083

db:
  dbQueries:
    getPlans: "Select * from plans order by planId DESC"
    insertPlan: "INSERT INTO plans(planName,planAmount,planDescription,planActive,planListingLimit,planDuration,reviewShow,contactShow) VALUES(?,?,?,?,?,?,?,?)"
    updatePlan: "UPDATE plans set planName=?,planAmount=?,planDescription=?,planActive=?, planListingLimit=?,planDuration=?,reviewShow=?,contactShow=? where planId=? "
    changePlanStatus: "UPDATE plans set planActive=? where planId=?"
    insertListing: "INSERT INTO listing(profileId,categoryId,addressId,contactId,listingName,listingDescription,minimumPrice,maximumPrice,website,listingImage,listingActive,listingVerify,listingTagLine)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)"
    insertListingTime: "INSERT INTO listingtime(listingId,mondayOpen,mondayClose,tuesdayOpen,tuesdayClose,wednesdayOpen,wednesdayClose,thursdayOpen,thursdayClose,fridayOpen,fridayClose,saturdayOpen,saturdayClose,sundayOpen,sundayClose)values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"
    getAllListing: "select l.listingId,l.profileId,l.categoryId,l.addressId,l.contactId,l.listingName,l.listingDescription,l.minimumPrice,l.maximumPrice,l.website,l.listingImage,l.listingActive,l.listingVerify,l.listingTagLine,a.city,c.categoryName,c.categorySmallIconURL,con.email from listing l, category c, address a, contact con where a.addressId=l.addressId and c.categoryId=l.categoryId and con.contactId=l.contactId"
    getListingTime: "select * from listingTime where listingId=?"
    getAllListingByBusiness: "select l.listingId,l.profileId,l.categoryId,l.addressId,l.contactId,l.listingName,l.listingDescription,l.minimumPrice,l.maximumPrice,l.website,l.listingImage,l.listingActive,l.listingVerify,l.listingTagLine,a.city,c.categoryName,c.categorySmallIconURL,con.email from listing l, category c, address a, contact con where a.addressId=l.addressId and c.categoryId=l.categoryId and con.contactId=l.contactId and l.profileId=?"
    changeListingActive: "UPDATE Listing set listingActive=? where listingId=?"
    changeListingVerify: "UPDATE Listing set listingVerify=? where listingId=?"
    getAllVerifiedListing: "select l.listingId,l.profileId,l.categoryId,l.addressId,l.contactId,l.listingName,l.listingDescription,l.minimumPrice,l.maximumPrice,l.website,l.listingImage,l.listingActive,l.listingVerify,l.listingTagLine,a.city,c.categoryName,c.categorySmallIconURL,con.email from listing l, category c, address a, contact con where a.addressId=l.addressId and c.categoryId=l.categoryId and con.contactId=l.contactId and l.listingVerify=true "